### ISSUE TITLE
Incorrect Percentage Calculation on Quiz Page

### ISSUE THREAD

**Issue by 26samaahmed** [acmcsufoss/acmcsuf.com#1081]
### What happened?

The calculation for the quiz results is miscalculated after adding the data for OSS, Game Dev, and ICPC.  The Game Dev results are always 0 as well.

![Screenshot 2024-05-04 131342](https://github.com/EthanThatOneKid/acmcsuf.com/assets/111910374/f97bf352-f030-4a63-b383-ebb2dfb286b9)

**Comment by 26samaahmed** [comment]
Reference #1059

**Comment by tmbkoren** [comment]
Game dev results in 0 because in src/lib/public/quiz/questions/types.ts TeamMatch, GAMEDEV is defined as 'Game Dev' with a space, thus being recorded as 'Game Dev' in responses. When calculating matches, `match = match?.toLowerCase() as TeamMatch;` is used, resulting in 'game dev' string. But in src/lib/public/board/data/teams.json, Game Dev team Id is "gamedev" without a space. 

When displaying quiz results, team data such as progress bar color is accessed using TEAMS[match]. 
```
<h2 class="match-title" style={`--team-color: ${TEAMS[match].color}`}>
      {match} <span>Team</span>
    </h2>
    <p>Click the teams below to see your next step</p>
    <div class="result-grid">
      <div
        class="result-grid-box"
        on:click|preventDefault|stopPropagation={() => showTeamDetails(TEAMS[match])}
        on:keydown|preventDefault|stopPropagation={() => showTeamDetails(TEAMS[match])}
        style={`--border-color: ${TEAMS[match].color}`}
        role="button"
        tabindex="0"
      >
```
Since it's trying to access TEAMS['game dev'], it returns nothing. 

Also, as a result of this, whenever you get game dev as your match, page simply doesn't render. 
<img width="1433" alt="image" src="https://github.com/user-attachments/assets/a6449679-cdda-4d39-96dd-7e8693fa45bc">

### Proposed solution : 
 in src/lib/public/quiz/questions/types.ts TeamMatch, change `GAMEDEV = 'Game Dev',` to `GAMEDEV = 'GameDev',`
 After doing the said change and making choices to get gamedev match: 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/4a01a2f7-d5df-4cf5-b31d-8677a6c48b05">

I don't see src/lib/public/quiz/questions/types.ts being used outside of quiz module, so there shouldn't be a problem. 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/0c2773c2-3550-48d4-97e2-2b9ed3a524ba">

**Comment by tmbkoren** [comment]
As for progress bar, issue is with the formula that calculates percentage. It is `{(talliedResponses[match] / data.questions.length) * 100}`. 
`data.questions.length` is a number of questions, which is always 13, while talliedResponses stores amount of matches for each team, which varies depending on the responses chosen, and the sum is variable, resulting in percentages being off. 
### My proposal:
change the formula to `{(talliedResponses[match] / sumOfTallies) * 100}`, where sumOfTallies is calculated by a function
```
 function totalTallies(tallies: Record<string, number>) {
    let totalTallies = 0;
    Object.values(tallies).forEach(value => totalTallies += value);
    return totalTallies;
  }
```
After doing the said change: 
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/52395479-ab68-436c-922d-82c920bcfae4">
Unfortunately, because of rounding it adds up to 99% sometimes. I have no fix for that(yet), and would take suggestions.
