### ISSUE TITLE
Marketing logo interference with marketing board face images

### ISSUE THREAD

**Issue by adriancancode** [acmcsufoss/acmcsuf.com#1103]
### What happened?

![marketing_issue](https://github.com/user-attachments/assets/4f4bc997-9eff-4bc8-a117-3cd165c45330)

The marketing logo looks like it moves right on top of my face image making it look a bit too close to my picture, compared to other team logos which appear more distant to the face images they are close to.

**Comment by 26samaahmed** [comment]
Resolved in https://github.com/EthanThatOneKid/acmcsuf.com/pull/1099/commits/46e75aa7f25f85c36b1fbd60667becff69e4c4df by shifting the animation to 45 degrees instead of 90 degrees. Look at picture for reference.

![Screenshot 2024-07-13 130847](https://github.com/user-attachments/assets/02f8231d-ec14-4655-b987-20970b39817b)
