### ISSUE TITLE
Support for real life locations

### ISSUE THREAD

**Issue by ghost** [acmcsufoss/acmcsuf.com#149]
### What's your idea?

Current:
![image](https://user-images.githubusercontent.com/54593375/137239773-aaf80d0f-9166-4565-8bdf-fead5e26ca11.png)

Use Google Calendar API to pull Google Maps location link.

Additionally, do string parsing to get rid of extraneous text in the location field.

**Comment by diamondburned** [comment]
I think it might be better to display just the short part of the location, e.g. "Titan Student Union", so that it appears in one line. Then, clicking on the location could bring up a dialog containing the embedded Google Maps/OpenStreetMap image and the full address.

Another way without making the address a link would be to make the card expand when it's clicked (as a dialog or similar). The full address could be shown there along with more information, like a longer description of the event.

**Comment by EthanThatOneKid** [comment]
To get the correct Google Maps link for free, we can add it to the bottom of the event's description (e.g. `GMAPS_LINK=https://goo.gl/maps/eZaNLwyTcDNJ7YWX9`).

> Then, clicking on the location could bring up a dialog containing the embedded Google Maps/OpenStreetMap image and the full address.

If anything we'd probably go with OpenStreetMaps over Google Maps since it is free. 

> Another way without making the address a link would be to make the card expand when it's clicked (as a dialog or similar). The full address could be shown there along with more information, like a longer description of the event.

I'd say, for now, we should go with the modal with more information/longer description/Google Maps link as a proof-of-concept. Once that feature is settled, we can try integrating OpenStreetMaps.

**Comment by ghost** [comment]
OpenStreetMap might bring up a lot of inaccuracies since it's based on user report.  To keep reliability, and for making this work well with mobile, Google Maps link might be the way to go.

**Comment by anhduy1202** [comment]
there's a something call mapbox that I usually use for map features but I don't know if it compatible with Svelte since I usually use it with react-map-gl, and I believe Google map API charges fee if it exceeds a certain amount of requests

Note: I think I found the mapbox for Svelte (ref: https://github.com/beyonk-adventures/svelte-mapbox?ref=madewithsvelte.com)

**Comment by k4rni** [comment]
Duplicate of #712.
