### ISSUE TITLE
title overflow

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#274]
### What happened?

![image](https://user-images.githubusercontent.com/8981287/150903600-784e07d8-cc8a-4ba8-9f37-389226df159f.png)
see image

**Comment by stephaniePocci** [comment]
# Fix for #274
I fixed the text overflow for the blog titles: 
![image](https://user-images.githubusercontent.com/54595424/191615290-efc61bd6-865f-4e76-aea8-9fc50bf9199e.png)
![image](https://user-images.githubusercontent.com/54595424/191616444-d515ebe8-94ad-4692-9aa3-6ee82ac70a93.png)

You can't really view my changes on vercel since I had to enable debug mode to take that screenshot, **so you may have to clone my [fork](https://github.com/stephaniePocci/acmcsuf.com) to check it via localhost** (pls let me know if there is a way I can enable the blogs to be viewed normally on vercel.) 

Also, I found additional text overflow when actually viewing the title on the blog page, so I'll be submitting a bug for that soon.
