### ISSUE TITLE
Mismatched join button hovering effect

### ISSUE THREAD

**Issue by MohamedHabarneh** [acmcsufoss/acmcsuf.com#335]
### What happened?

![website_button](https://user-images.githubusercontent.com/92408806/158038145-48e3ff1e-0855-48b7-8cbe-2d85f56628b8.png)
![website_button2](https://user-images.githubusercontent.com/92408806/158038148-c85f078c-7874-4eb1-a5a6-8fbbb538fb87.png)

The hovering effect of the join button on the event's card is different than the rest of the buttons on the website. Keep in mind, that the color of the join button in the event card should be consistent with the ACM path.

**Comment by EthanThatOneKid** [comment]
The hover effect on both these buttons are different. To keep things consistent, I think we should go with the hover effect where the text changes colors instead of the background-color of the button. This might be possible by consolidating the buttons seen in the two screenshots into a single, shared button component.

Decision reached by @anhduy1202, @EthanThatOneKid, and others via Discord

**Comment by anhduy1202** [comment]
PR: https://github.com/EthanThatOneKid/acmcsuf.com/pull/338
