### ISSUE TITLE
add full name to blog posts instead of github username

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#488]
### What's your idea?

![image](https://user-images.githubusercontent.com/8981287/170615287-436cffa6-9782-4c4f-87d8-6400429b18db.png)
Currently the blog posts only return the display name but I'd like it to return the full name instead and maybe the bio?
![image](https://user-images.githubusercontent.com/8981287/170615513-e4f3fc99-63e9-41a4-9130-154c89525f71.png)

**Comment by EthanThatOneKid** [comment]
Nice idea! Fwiw, if the author happens to be a current or previous ACM at CSUF board member, their full name should already be available via our `/src/lib/constants/officers.json` file.

**Comment by jaasonw** [comment]
I saw that in the code but I don't actually see it working as all blog posts were by board members

**Comment by EthanThatOneKid** [comment]
I recently made a branch [`test/officer-github-compat`](https://github.com/EthanThatOneKid/acmcsuf.com/tree/test/officer-github-compat) to see if it was working. Since it isn’t, [`getOfficerByGhUsername`](https://github.com/EthanThatOneKid/acmcsuf.com/blob/05e2ad9417943751eaa8c1371f4ef03283555f9e/src/routes/blog/_query.ts#L51) might need further testing.

**Comment by jaasonw** [comment]
update: after finally updating my profile to have a github username it still does not work

**Comment by jaasonw** [comment]
![image](https://user-images.githubusercontent.com/8981287/198935526-b97467ab-4788-4fa9-a52a-ff622f2d2a42.png)

**Comment by jaasonw** [comment]
![image](https://user-images.githubusercontent.com/8981287/198936228-e8b8a16b-a8b7-4a7c-b891-532426f30b14.png)

**Comment by EthanThatOneKid** [comment]
Followed up in #650.
