### ISSUE TITLE
image carousel for about page

### ISSUE THREAD

**Issue by jaasonw** [acmcsufoss/acmcsuf.com#506]
### What's your idea?

because we're changing the path icons these need to be updated
![image](https://user-images.githubusercontent.com/8981287/184295940-4d29dd40-b080-4f96-8676-36bd26e03d6c.png)

but this looks weird
![image](https://user-images.githubusercontent.com/8981287/184296059-84aff5cf-a184-4565-9249-54e22807c8d7.png)

so my alternative proposal is to replace this with a photo carousel

**Comment by EthanThatOneKid** [comment]
We used to maintain a carousel component but removed it in #280 in exchange for a simpler, vertical list component. Carousel components are notoriously difficult to get 100% right, and especially since we are a website aiming to provide static information, it has proven difficult in the past to justify maintaining a JavaScript carousel. 

Despite our history with carousels, I am open to giving it another try from scratch assuming we create something of a common carousel component that is implemented in multiple places on the site e.g. your proposed image carousel. 

Note: acmcsuf.com aims to minimize the client's need for JavaScript, so making the carousel as HTML/CSS-friendly as possible is the highest priority. If our carousel cannot function without JavaScript, then it will break when JavaScript fails to load for a user with an unreliable connection. This case where JavaScript fails to load [for whatever reason] at worst will confuse acmcsuf.com visitors and waste their time.

**Comment by k4rni** [comment]
Carousels require JavaScript, which we aim to avoid on acmcsuf.com for accessibility purposes. Instead, we will consistently update the image each semester to show the growth of our club as a whole.

acmUCLA makes use of a carousel in their website (https://www.uclaacm.com/) while using JS. However, once JS is disabled, the images become still.
- We could reference this to create our own carousel, but there will be separate pages on the wiki page/gallery page to populate with images
