### ISSUE TITLE
Board member card socials affecting badge positioning.

### ISSUE THREAD

**Issue by AlanCortez1337** [acmcsufoss/acmcsuf.com#634]
After what seemed like 12 years, my badge's dimensions are correct I triple checked it. The issue I'm starting to see is that the people with the card social feature Diamond made are affected by this. Unless I have literally gone insane, look closer at Ethan's, Diamond's and my badges compared to the others who do not have their socials connected yet.
![badge card interaction](https://user-images.githubusercontent.com/78040578/197444929-a13b40b2-bcc8-41e3-beaa-bc47152d816b.PNG)

_Originally posted by @AlanCortez1337 in https://github.com/EthanThatOneKid/acmcsuf.com/issues/632#issuecomment-1288378512_

**Comment by diamondburned** [comment]
This is related to (and very likely depends on) issue https://github.com/EthanThatOneKid/acmcsuf.com/issues/348. As long as we manually do the masks, we can't correctly fix this.

**Comment by EthanThatOneKid** [comment]
This issue is referring to the current way that we serve our officer images: with the diamond mask preprocessed into the webp. I think that Alan took the opportunity to resolve the existing webp inconsistencies for now as part of #632 (since #632 already resolves one issue, it would be better to resolve this issue in a separate PR). 

I’m thinking to resolve #348, we will replace all of the images with their square-sized counterparts (currently on Figma) where the diamond mask is applied using CSS or SVG magic.
