### ISSUE TITLE
Genuary page does not include linked media from Genuary threads

### ISSUE THREAD

**Issue by jiink** [acmcsufoss/acmcsuf.com#769]
### What happened?

The pinned messages of each genuary thread are automatically checked for media, but the process does not consider that submissions may be embedded links (cdn.discordapp, imgur.com, etc) to media (mp4, gif, etc) rather than a direct Discord attachment. As a result, some Genuary submissions are missing from the [Genuary page](https://acmcsuf.com/genuary/2023).

**Comment by EthanThatOneKid** [comment]
### Problem

This is caused by a couple of if-statements in need of refactoring!

<https://github.com/EthanThatOneKid/acmcsuf.com/blob/cfb616e655f2a70b284e6f7b8426bf32c15eb4b7/scripts/transform-genuary.js#L10-L17>

### Solution

Add a function to gather the URLs.

```js
function getURLs(str, validDomains) {
  const regex = /(https?:\/\/[^\s]+)/g; // Regular expression to match URLs
  const urls = str.match(regex) || []; // Extract URLs from the string

  return urls.filter(url => { // Filter the list of URLs
    const domain = url.match(/https?:\/\/([^/]+)/)[1]; // Extract the domain from the URL
    return validDomains.includes(domain); // Return true if the domain is in the list of valid domains
  });
}
```

Get the media-associated URLs from each message. Check that the media-associated message URLs length is greater than 0 if the message attachments are null or the message attachments length is 0.
