### ISSUE TITLE
Enable checkmarks for task list on the ACM blog posts

### ISSUE THREAD

**Issue by stephaniePocci** [acmcsufoss/acmcsuf.com#814]
### What's your idea?

I just made a [blog post](https://acmcsuf.com/blog/813) using markdown to create a checkable task list, but users are unable to tick the boxes as intended it's very very cringe :(
![image](https://cdn.discordapp.com/attachments/757993798243451041/1084984185963417600/image.png)

**Comment by jaasonw** [comment]
what would being able to click the checkboxes achieve? or what should the intended behavior be? should they just checkable client side with no persisted state? or should it reflect for all users? i'm assuming the former but just making sure you dont mean something else

**Comment by EthanThatOneKid** [comment]
> what would being able to click the checkboxes achieve? or what should the intended behavior be? should they just checkable client side with no persisted state? or should it reflect for all users? i'm assuming the former but just making sure you dont mean something else

I think it would be cool to persistently store the checkbox values per blog post with localStorage. 

Thank you for the questions and suggestion @jaasonw.

**Comment by jaasonw** [comment]
off the top of my head, this sounds a little nontrivial to implement without either writing some of our own parsing logic to id each checkbox and then using that to store the individual ids. it'd be a bit more trivial to just regex remove all the disabled's from the checkboxes and call it a day. really depends on how much effort we wanna invest in this feature and if we should just bring in a custom markdown parser instead of trying to keep bolting patches onto whatever github gives us (see: essentially copy pasting github's css for code block styling, not sure who did this really)

**Comment by k4rni** [comment]
Marked as stale.
